/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubmissionsImport } from './routes/submissions'
import { Route as ProfileImport } from './routes/profile'
import { Route as AuthImport } from './routes/auth'
import { Route as AssignmentsImport } from './routes/assignments'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SubmissionsRoute = SubmissionsImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AssignmentsRoute = AssignmentsImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/submissions': typeof SubmissionsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/submissions': typeof SubmissionsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/submissions': typeof SubmissionsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assignments' | '/auth' | '/profile' | '/submissions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assignments' | '/auth' | '/profile' | '/submissions'
  id: '__root__' | '/' | '/assignments' | '/auth' | '/profile' | '/submissions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  SubmissionsRoute: typeof SubmissionsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  SubmissionsRoute: SubmissionsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/assignments",
        "/auth",
        "/profile",
        "/submissions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/assignments": {
      "filePath": "assignments.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/submissions": {
      "filePath": "submissions.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
