apiVersion: apps/v1
kind: Deployment
metadata:
  name: edukita-lms
  labels:
    app: edukita-lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edukita-lms
  template:
    metadata:
      labels:
        app: edukita-lms
    spec:
      containers:
      - name: edukita-lms-app
        image: docker.io/hkimm/edukita-lms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: edukita-lms-config
        - secretRef:
            name: edukita-lms-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30